### ISSUE TITLE
Compilation error: 'btn' was not declared in this scope

### ISSUE THREAD

**Issue by eugenystrigulin** [AlexGyver/GyverTwink#21]
Перепробывал все помоему. и прямо все библиотеки копировал удалив предыдущие и поочередно добавляя библиотеки. все шло норм до......Compilation error: 'btn' was not declared in this scope. даже плату на 2.7.4 поменял Compilation error: 'btn' was not declared in this scope

**Comment by AlexGyver** [comment]
Не нужно ничего перепробовать, достаточно один раз прочитать гайд и сделать как там написано

![image](https://github.com/user-attachments/assets/5ac5a664-8723-4b93-8e38-aca0adf41bce)
